/* eslint-disable global-require */

const images = {
  200: {uri: 'https://i.imgur.com/PT8obra.png'},
  201: {uri: 'https://i.imgur.com/PT8obra.png'},
  202: {uri: 'https://i.imgur.com/PT8obra.png'},
  210: {uri: 'https://i.imgur.com/PT8obra.png'},
  212: {uri: 'https://i.imgur.com/PT8obra.png'},
  221: {uri: 'https://i.imgur.com/PT8obra.png'},
  230: {uri: 'https://i.imgur.com/PT8obra.png'},
  231: {uri: 'https://i.imgur.com/PT8obra.png'},
  232: {uri: 'https://i.imgur.com/PT8obra.png'},
  300: {uri: 'https://i.imgur.com/hC4zUDu.png'},
  301: {uri: 'https://i.imgur.com/hC4zUDu.png'},
  302: {uri: 'https://i.imgur.com/hC4zUDu.png'},
  310: {uri: 'https://i.imgur.com/hC4zUDu.png'},
  311: {uri: 'https://i.imgur.com/hC4zUDu.png'},
  312: {uri: 'https://i.imgur.com/hC4zUDu.png'},
  313: {uri: 'https://i.imgur.com/p8T0gBI.png'},
  314: {uri: 'https://i.imgur.com/p8T0gBI.png'},
  321: {uri: 'https://i.imgur.com/p8T0gBI.png'},
  500: {uri: 'https://i.imgur.com/fkoGh1r.png'},
  501: {uri: 'https://i.imgur.com/fkoGh1r.png'},
  520: {uri: 'https://i.imgur.com/fkoGh1r.png'},
  521: {uri: 'https://i.imgur.com/fkoGh1r.png'},
  531: {uri: 'https://i.imgur.com/fkoGh1r.png'},
  504: {uri: 'https://i.imgur.com/jAp3oMa.png'},
  503: {uri: 'https://i.imgur.com/jAp3oMa.png'},
  502: {uri: 'https://i.imgur.com/jAp3oMa.png'},
  522: {uri: 'https://i.imgur.com/jAp3oMa.png'},
  511: {uri: 'https://i.imgur.com/jAp3oMa.png'},
  611: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  612: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  600: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  601: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  602: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  615: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  616: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  620: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  621: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  622: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  700: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  711: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  721: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  731: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  741: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  751: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  761: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  762: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  771: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  781: {uri: 'https://i.imgur.com/RnBjjTq.png'},
  800: {uri: 'https://imgur.com/HEtR4ZA.png'},
  801: {uri: 'https://i.imgur.com/TiG6vKR.png'},
  802: {uri: 'https://i.imgur.com/TiG6vKR.png'},
  803: {uri: 'https://i.imgur.com/QsIRcRq.png'},
  804: {uri: 'https://i.imgur.com/QsIRcRq.png'},
  Clear: {uri: 'https://imgur.com/HEtR4ZA.png'},
  Hail: {uri: 'https://i.imgur.com/hC4zUDu.png'},
  'Heavy Cloud': {uri: 'https://i.imgur.com/QsIRcRq.png'},
  'Light Cloud': {uri: 'https://i.imgur.com/TiG6vKR.png'},
  'Heavy Rain': {uri: 'https://i.imgur.com/jAp3oMa.png'},
  'Light Rain': {uri: 'https://i.imgur.com/fkoGh1r.png'},
  Showers: {uri: 'https://i.imgur.com/p8T0gBI.png'},
  Sleet: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  Snow: {uri: 'https://i.imgur.com/YKE0Zn1.png'},
  Thunder: {uri: 'https://i.imgur.com/PT8obra.png'},
};

export default weather => images[weather];
